### ISSUE TITLE
Training time 

### ISSUE THREAD

**Issue by SISTMrL** [cjw2021/QAHOI#1]
Hello, Junwen Chen:
       How wonderful work it is, I want to know the training time of your work, looking forward to your reply, thanks!
Best regards!

**Comment by cjw2021** [comment]
Thanks for your interest in our work.
We train QAHOI with 8GPUs (A6000 x 8), and the batch size is 16 (8x2).
For each epoch, the training time of QAHOI with Swin-Tiny, Swin-Base is 20 and 31 minutes, respectively.
QAHOI with Swin-Large is trained by using `torch.utils.checkpoint` to save memory, and it takes 1h per epoch.

**Comment by xuliwalker** [comment]
Hi Junwen:

Thanks for your great work! I wonder is it possible to train QAHOI with Swin-Large on 8 V100 GPUs, which has 32GB memory. Thanks!

**Comment by cjw2021** [comment]
Thanks for your interest.
Training QAHOI with Swin-Large on A6000 uses over 40GB of memory. 
If you want to train on V100, you can try to use fewer

- feature maps from the backbone (one or two) 
- layers of the deformable transformer encoder and decoder
- anchors

**Comment by xuliwalker** [comment]
> Thanks for your interest. Training QAHOI with Swin-Large on A6000 uses over 40GB of memory. If you want to train on V100, you can try to use fewer
> 
> * feature maps from the backbone (one or two)
> * layers of the deformable transformer encoder and decoder
> * anchors

Thanks for your reply! In fact, I did not change anything in your default training config or the code except turning on the use_checkpoint flag, and managed to train QAHOI with Swin-Large on V100 GPUs, which seems like conflicting with your reply of 40GB of memory usage. So I wonder did I miss anything? Thanks!

**Comment by cjw2021** [comment]
I am sorry for not explaining this clearly.
The maximum memory used by QAHOI with Swin-Large in training is over 40GB.
So you can train with the setting of `use_checkpoint`, but it will break down by OOM later.

**Comment by xuliwalker** [comment]
> I am sorry for not explaining this clearly. The maximum memory used by QAHOI with Swin-Large in training is over 40GB. So you can train with the setting of `use_checkpoint`, but it will break down by OOM later.

Hi thanks for your reply sincerely! I tried training QAHOI with Swin-Large on 8 V100s and It have not break down after 30 epochs. But when I loaded the trained SOTA model and wanted to further finetune this SOTA model, it broke down by OOM once the training began. So I wonder do you have any clues about this problem.  I list the training command below for your reference and thanks for your help!

python3 -m torch.distributed.launch \
        --nproc_per_node=8 \
        --use_env main.py \
        --backbone swin_large_384 \
        --resume params/QAHOI_swin_large_384_22k_mul3.pth \
        --output_dir logs/swin_large_384_22k_mul3 \
        --epochs 200 \
        --num_feature_levels 3 \
        --num_queries 300 \
        --use_nms
        --use_checkpoint
