### ISSUE TITLE
Question about the performance influence of the resolution of pretrained swin transformer on the HICO-DET

### ISSUE THREAD

**Issue by truetone2022** [cjw2021/QAHOI#10]
Have you tried to train the QAHOI which is based on the ImageNet-22K 224x224 pre-trained swin transformer backbone?

**Comment by cjw2021** [comment]
![image](https://user-images.githubusercontent.com/81892872/159633840-614de5f1-5f0f-42e9-88dd-4ef847684350.png)

Here are some other experiments we did.
The Swin-Base* in this table is based on the ImageNet-22K with 224x224 resolution.

**Comment by truetone2022** [comment]
Thanks! Furthermore, I wonder why the QAHOI with R50 backbone cannot surpass the QPIC with R50 backbone? Intuitively,  deformable-detr-r50 should perform better than detr-r50 on HICO-DET dataset

**Comment by truetone2022** [comment]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/45789117/159634953-b1f2d124-0e33-4cc9-b6e8-20ebf969ed54.png">
Both of them are fine-tuned on COCO, but QAHOI cannot acquire a huge performance boost like QPIC, it's strange.

**Comment by cjw2021** [comment]
|                 |  epoch  |    AP    |   AP-S   |   AP-M   |   AP-L   |
| --------------- | :-----: | :------: | :------: | :------: | :------: | 
| Deformable DETR |   50    | **44.5** | **27.1** | **47.6** |   59.6   |
| DETR            | **500** |   42.0   |   20.5   |   45.8   | **61.1** |

We use the deformable-detr-r50 trained 50 epochs on COCO.

I think there are three main reasons that QAHOI-r50-fine is lower that QPIC-r50-fine:

1. The AP-L of deformable-detr-r50 is lower than detr-r50.
    - QPIC only use the low-resolution high-level feature map, and this is beneficial for large object detection. There are 600 HOI categories, although we have not evaluated the spatial distribution of each category. The large size target may be more important than the median or small ones.
    - The deformable-detr-r50 trained 150 epochs has better performance. Training a deformable-detr with higher AP-L may get better for the HOI task.
2. The deformable-detr-r50 uses four feature maps.
    - As the multi-scale experiments of QAHO-swin-tiny, using three feature maps is better.
3. The attention mechanism.
    - The attention mechanism of the DETR to achieve global attention may be better than Deformable-DETR. For reference, you can check this paper. [Vision Transformer with Deformable Attention](https://arxiv.org/abs/2201.00520v1)
    - Although QAHOI uses multi-scale feature maps to improve the detection part, the recognition part which requires global semantic information may be weaker than QPIC.

If you have any ideas, feel free to point them out.

**Comment by truetone2022** [comment]
Very thanks for your helpful reply!
