### ISSUE TITLE
Question about iterative box refinement

### ISSUE THREAD

**Issue by truetone2022** [cjw2021/QAHOI#11]
Have you tried using the iterative box refinement module in deformable detr? Is the iterative box refinement module helpful for HOI detection? Thanks for any helpful reply!

**Comment by cjw2021** [comment]
Yes, we have tried iterative_bbox and two_stage module.
However, the performance is lower than the original, and using iterative_bbox or two_stage for all of the feature maps is hard to train.

**Comment by truetone2022** [comment]
Very thanks for your helpful reply!
