### ISSUE TITLE
Question about the performance on V-COCO dataset

### ISSUE THREAD

**Issue by bingnanG** [cjw2021/QAHOI#13]
Thanks for your great works!!  :) 
Have u ever tried to train the QAHOI on V-COCO dataset? I donot find the results on V-COCO in paper.
If you could give me any help i would be appreciate.Thank you for your help.

**Comment by cjw2021** [comment]
We have not yet trained QAHOI on VCOCO, but we provide the training code and evaluation code.

**Comment by bingnanG** [comment]
邮件已收到！！
