### ISSUE TITLE
How to train QPIC with Swin-Tiny

### ISSUE THREAD

**Issue by hutuo1213** [cjw2021/QAHOI#17]
Hello, can you provide backbone for swin-T qpic training parameter details，
I found in training that the same setting for each interaction mAP value is 0.
How to train QPIC with Swin-Tiny, the mAP of the first 20 epochs we train is almost all 0. Thank you very much!

**Comment by cjw2021** [comment]
We use the same setting as QPIC-ResNet-50 to train QPIC-Swin-T.
Here is the [backbone.py](https://gist.github.com/cjw2021/3d3e299cf92538eb92a31452800b757c).
