### ISSUE TITLE
parameter --use_nms is not used

### ISSUE THREAD

**Issue by ilovecv** [cjw2021/QAHOI#3]
Hi,

Thank you very much for sharing the codes. It's great!
For the --use_nms parameter defined here https://github.com/cjw2021/QAHOI/blob/main/main.py#L138,
 it looks like it is not used.

**Comment by cjw2021** [comment]
Thanks for your interest in our work.
NMS process is used during evaluation. So the `--use_nms` option is used when the evaluator is initialized.
See this line https://github.com/cjw2021/QAHOI/blob/bb7f5fd79e2f33980a41190f9f37460f7c22e67b/engine.py#L119
