### ISSUE TITLE
question about the swin-tiny model

### ISSUE THREAD

**Issue by truetone2022** [cjw2021/QAHOI#4]
I can replicate the result of the swin-large* model. But i can't replicate the result of the swin-tiny model with the same training command

python -m torch.distributed.launch \
        --nproc_per_node=8 \
        --use_env main.py \
        --backbone swin_tiny \
        --pretrained params/swin_tiny_patch4_window7_224.pth \
        --output_dir logs/swin_tiny_mul3 \
        --epochs 150 \
        --lr_drop 120 \
        --num_feature_levels 3 \
        --num_queries 300 \
        --use_nms

![image](https://user-images.githubusercontent.com/45789117/149760175-4d397ee6-8b7e-4891-92c4-f345436d6499.png)

**Comment by cjw2021** [comment]
Could you attach the GPU devices and environment you used？
We train the Swin-Tiny model with 8xA6000, Pytorch 1.9, and CUDA 11.2.

**Comment by truetone2022** [comment]
I used 8*A100, pytorch1.8 and CUDA 11.2 for training swin-tiny model. Now i can get 27.44mAP, but there still exists 1 mAP gap.

**Comment by cjw2021** [comment]
Thanks for your reply.
We have not trained the model on A100 and hope you can do a few more training sessions and test with the best model.
We report the model with the highest mAP during training rather than the model of the last epoch.
