### ISSUE TITLE
Test QAHOI on custom images

### ISSUE THREAD

**Issue by mjantoun** [cjw2021/QAHOI#5]
I would like to test the model on images other than the HICO-DET and V-COCO datasets.
I do not have ground truth detection. I only found the eval code but it requires ground truth detections for evaluation.

**Comment by cjw2021** [comment]
Thanks for your interest in our work.
You can use the pre-trained model to infer custom images with this [inference](https://gist.github.com/cjw2021/5629f018ba00b2bed9ca73b9887e9b91) code.

- Put the code in the same directory as main.py.
- The [corre_hico.npy](https://drive.google.com/file/d/1VBBFC7mUJpVMn79dvlq4nIRHwPXWwm9A/view?usp=sharing) file is required.
- Usage

```bash
python inference.py --resume params/QAHOI_swin_tiny_mul3.pth --corre_hico_path [xxx/corre_hico.npy] --backbone swin_tiny --num_feature_levels 3 --image test.jpg --top 5

python inference.py --resume params/QAHOI_swin_large_384_22k_mul3.pth --corre_hico_path [xxx/corre_hico.npy] --backbone swin_large_384 --num_feature_levels 3 --image test.jpg --top 5
```
- `--top` : 1 to 10
- `result.png` will save in the current directory.

**Comment by LukeeCR** [comment]
thanks for inference code, but the output of outputs = model(img) is always the same when i chaneg images

**Comment by LukeeCR** [comment]
How about the model base of inference

**Comment by cjw2021** [comment]
> 

- Usage

```bash
python inference.py --resume params/QAHOI_swin_tiny_mul3.pth --corre_hico_path [xxx/corre_hico.npy] --backbone swin_tiny --num_feature_levels 3 --image test.jpg --top 5

python inference.py --resume params/QAHOI_swin_base_384_22k_mul3.pth --corre_hico_path [xxx/corre_hico.npy] --backbone swin_base_384 --num_feature_levels 3 --image test.jpg --top 5

python inference.py --resume params/QAHOI_swin_large_384_22k_mul3.pth --corre_hico_path [xxx/corre_hico.npy] --backbone swin_large_384 --num_feature_levels 3 --image test.jpg --top 5
```
