### ISSUE TITLE
Is it possible for you to share a training log of Swin-T model?

### ISSUE THREAD

**Issue by JacobYuan7** [cjw2021/QAHOI#6]
Hello author, Thx for your great work! As I am using your repo, I find this model hard to converge compared to normal object detection. Thus, is it possible for you to share a training log of Swin-T model (or any other model)? Many thanks for that!

**Comment by cjw2021** [comment]
Here is the [log.txt](https://gist.github.com/cjw2021/a2a4db82a366428d241f72a0c1a24396) of QAHOI-Swin-Tiny with (x1,x2,x3 multi-scale feature maps) trained from scratch.

For saving test time, we use the QPIC's evaluation [code](https://github.com/hitachi-rd-cv/qpic/blob/main/datasets/hico_eval.py) during training, which is faster than the evaluation code of [GGNet](https://github.com/SherlockHolmes221/GGNet/blob/main/src/lib/eval/hico_eval_de_ko.py), and the result is slightly higher than GGNet's. 
And the NMS process was also not used during training.

The final result is obtained by using GGNet's evaluator with the NMS process.

**Comment by JacobYuan7** [comment]
@cjw2021 Many thanks! That's a good reference.
