### ISSUE TITLE
Can you share your visualization script?

### ISSUE THREAD

**Issue by sunggukcha** [cjw2021/QAHOI#8]
Hello @cjw2021 ! Thanks for your great works!

Can you share your visalization script?
Also, if you already have distributed demo script and I am missing it, please let me know.

Regards,
Sungguk Cha

**Comment by cjw2021** [comment]
Thanks for your interests in our work.
We have provided the inference [code](https://github.com/cjw2021/QAHOI/issues/5) for visualization, you can use it directly.
