### ISSUE TITLE
Training on vcoco dataset

### ISSUE THREAD

**Issue by OBVIOUSDAWN** [cjw2021/QAHOI#9]
Hello @cjw2021  ! Thanks for your great works!
I tried to train this model on vcoco dataset to save some time.But when i build the vcoco dataset,i meet the same error on 
`  File "/root/autodl-tmp/QAHOI-main/models/matcher.py", line 53, in forward
    cost_verb_class = -(out_verb_prob.matmul(tgt_verb_labels_permute) / \
RuntimeError: mat1 dim 1 must match mat2 dim 0`

Do you have the training code of vcoco in feature?My vcoco dataset training followed with "https://github.com/hitachi-rd-cv/qpic" to add vcoco.py and vcocoeval.py in dataset and fix it,If you could give me any help i would be appreciate.Thank you for your help.

**Comment by cjw2021** [comment]
Thanks for your interests in our work.
We are now testing the code of training on v-coco.
Some settings in this version are only for HICO-DET.
Could you share your modification and wait for our update.

**Comment by cjw2021** [comment]
I update the code for V-COCO. Please try the latest code.
